# Generated by Django 5.1.2 on 2024-10-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'классификиция',
                'verbose_name_plural': 'классификиции',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('years', models.IntegerField(verbose_name='лет опыта')),
                ('months', models.IntegerField(verbose_name='месяцев опыта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='#', verbose_name='аватар')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.classification', verbose_name='классификация')),
            ],
            options={
                'verbose_name': 'врач',
                'verbose_name_plural': 'врачи',
            },
        ),
    ]
