# Generated by Django 5.1.2 on 2024-10-31 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0003_alter_diagnostic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='время записи'),
        ),
    ]
