# Generated by Django 5.1.2 on 2024-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0004_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='причина записи'),
        ),
    ]
